[project]
name = "rss-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tran PHong", email = "tran.bp@dyson.com" }
]
requires-python = ">=3.12"
dependencies = [
    "certifi>=2026.7.22",
    "feedgen>=1.0.0",
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.3",
]

[project.scripts]
rss-generator = "rss_generator:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"
